# Generated by Django 3.1.3 on 2022-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220818_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
